#!/usr/bin/env node
// Turns each stock Shopify notification template under marketing/notifications/stock/
// into the branded, ready-to-paste copy next to it. Three mechanical edits, nothing else:
//   1. the stock accent-colour <style> block is replaced with lib/brand-style.css
//   2. lib/footer-social.html is inserted before the footer's disclaimer paragraph
//   3. a one-line Liquid comment naming the source is prepended
// Manifest-driven and fail-closed: ids come from manifest.json, never a glob; every
// anchor must resolve exactly once; the stock snapshot must match its recorded hash;
// any refusal fails the whole run and, in generate mode, writes nothing.
//
//   node scripts/notifications/brand.mjs            regenerate every branded file
//   node scripts/notifications/brand.mjs --check    compare in memory, write nothing
//
// marketing/notifications/README.md documents the surface.

import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, writeFileSync, renameSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');

export const STOCK_STYLE_BLOCK = [
  '<style>',
  '.button__cell { background: {{ shop.email_accent_color }}; }',
  '.actions-buttons .button__cell--primary { background-color: {{ shop.email_accent_color }}; }',
  'a, a:hover, a:active, a:visited { color: {{ shop.email_accent_color }}; }',
  '</style>',
].join(' ');

export const FOOTER_TABLE_ANCHOR = '<table class="row footer">';
export const DISCLAIMER_ANCHOR = '<p class="disclaimer__subtext">';

export class BrandError extends Error {
  constructor(id, anchor, detail) {
    super(`${id}: refused (${anchor}): ${detail}`);
    this.id = id;
    this.anchor = anchor;
    this.detail = detail;
  }
}

export function normalizeWhitespace(text) {
  return text.replace(/\s+/g, ' ').trim();
}

export function sha256(text) {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

export function commentLine(id) {
  return `{%- comment -%}Generated by scripts/notifications/brand.mjs from marketing/notifications/stock/${id}.liquid. Do not hand-edit: change marketing/notifications/lib/ and regenerate.{%- endcomment -%}\n`;
}

function indexesOf(haystack, needle) {
  const out = [];
  let i = haystack.indexOf(needle);
  while (i !== -1) {
    out.push(i);
    i = haystack.indexOf(needle, i + needle.length);
  }
  return out;
}

function commentRanges(text) {
  const ranges = [];
  const re = /{%-?\s*comment\s*-?%}[\s\S]*?{%-?\s*endcomment\s*-?%}/g;
  let m;
  while ((m = re.exec(text)) !== null) ranges.push([m.index, m.index + m[0].length]);
  return ranges;
}

function insideComment(ranges, index) {
  return ranges.some(([a, b]) => index >= a && index < b);
}

function requireOnce(id, anchor, occurrences, ranges) {
  const outside = occurrences.filter((i) => !insideComment(ranges, i));
  if (occurrences.length !== outside.length) {
    throw new BrandError(id, anchor, 'anchor found inside a Liquid comment');
  }
  if (outside.length === 0) throw new BrandError(id, anchor, 'anchor not found');
  if (outside.length > 1) {
    throw new BrandError(id, anchor, `anchor found ${outside.length} times, expected exactly once`);
  }
  return outside[0];
}

function lineIndent(text, index) {
  const lineStart = text.lastIndexOf('\n', index - 1) + 1;
  const prefix = text.slice(lineStart, index);
  if (!/^[ \t]*$/.test(prefix)) return null;
  return prefix;
}

// Locate the two regions in a stock template. Returns { styleStart, styleEnd, footerStart }.
export function locateAnchors(stock, id, override) {
  const ranges = commentRanges(stock);
  let styleStart;
  let styleEnd;
  if (override && override.styleAnchor) {
    const at = requireOnce(id, 'style', indexesOf(stock, override.styleAnchor), ranges);
    styleStart = at;
    styleEnd = at + override.styleAnchor.length;
  } else {
    const blocks = [];
    const re = /<style[^>]*>[\s\S]*?<\/style>/g;
    let m;
    while ((m = re.exec(stock)) !== null) {
      if (m[0].includes('shop.email_accent_color')) blocks.push([m.index, m.index + m[0].length]);
    }
    const at = requireOnce(id, 'style', blocks.map((b) => b[0]), ranges);
    const block = blocks.find((b) => b[0] === at);
    if (normalizeWhitespace(stock.slice(block[0], block[1])) !== STOCK_STYLE_BLOCK) {
      throw new BrandError(id, 'style', 'accent-colour style block differs from the known stock block');
    }
    styleStart = block[0];
    styleEnd = block[1];
  }

  // The insertion point must sit inside the footer table whether it came from the stock disclaimer
  // anchor or from a manifest override: an override that resolves to the body-side disclaimer
  // paragraph (six stock templates carry one) would otherwise brand "successfully" in the wrong place.
  const tableAt = requireOnce(id, 'footer-table', indexesOf(stock, FOOTER_TABLE_ANCHOR), ranges);
  let footerStart;
  let footerAnchorName;
  if (override && override.footerAnchor) {
    footerAnchorName = 'footer';
    footerStart = requireOnce(id, footerAnchorName, indexesOf(stock, override.footerAnchor), ranges);
  } else {
    footerAnchorName = 'disclaimer';
    footerStart = requireOnce(id, footerAnchorName, indexesOf(stock, DISCLAIMER_ANCHOR), ranges);
  }
  if (footerStart < tableAt) {
    throw new BrandError(id, footerAnchorName, 'disclaimer paragraph precedes the footer table');
  }
  if (stock.slice(tableAt, footerStart).includes('</table>')) {
    throw new BrandError(id, footerAnchorName, 'disclaimer paragraph is not inside the footer table');
  }
  if (lineIndent(stock, footerStart) === null) {
    throw new BrandError(id, 'footer', 'insertion point is not at the start of a line');
  }
  if (styleEnd > footerStart) throw new BrandError(id, 'footer', 'footer anchor precedes the style block');
  return { styleStart, styleEnd, footerStart };
}

export function brandTemplate(stock, { id, css, social, override }) {
  if (stock.charCodeAt(0) === 0xfeff) throw new BrandError(id, 'input', 'stock file starts with a BOM');
  if (stock.includes('\r')) throw new BrandError(id, 'input', 'stock file contains a carriage return');
  const { styleStart, styleEnd, footerStart } = locateAnchors(stock, id, override);
  const indent = lineIndent(stock, footerStart);
  const output =
    commentLine(id) +
    stock.slice(0, styleStart) +
    '<style>\n' + css + '  </style>' +
    stock.slice(styleEnd, footerStart) +
    social.replace(/\s+$/, '') + '\n' + indent +
    stock.slice(footerStart);
  const body = stock.slice(0, styleStart) + stock.slice(styleEnd);
  const accentRemaining = indexesOf(body, 'email_accent_color').length;
  return { output, accentRemaining };
}

export function paths(root = REPO_ROOT) {
  const dir = join(root, 'marketing', 'notifications');
  return {
    dir,
    manifest: join(dir, 'manifest.json'),
    stockDir: join(dir, 'stock'),
    css: join(dir, 'lib', 'brand-style.css'),
    social: join(dir, 'lib', 'footer-social.html'),
    branded: (id) => join(dir, `${id}.liquid`),
    stock: (id) => join(dir, 'stock', `${id}.liquid`),
  };
}

export function readManifest(root) {
  const p = paths(root);
  const manifest = JSON.parse(readFileSync(p.manifest, 'utf8'));
  if (!manifest.templates || typeof manifest.templates !== 'object') {
    throw new Error('manifest.json: missing "templates" object');
  }
  return manifest;
}

function liquidIds(dir) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.liquid'))
    .map((f) => f.slice(0, -'.liquid'.length))
    .sort();
}

// Shared by generate and check.
// Returns { outputs: Map<id, string>, problems: string[], notes: string[], expectedBranded: string[] }.
export function plan(root = REPO_ROOT) {
  const p = paths(root);
  const problems = [];
  const notes = [];
  const outputs = new Map();
  const manifest = readManifest(root);
  const ids = Object.keys(manifest.templates).sort();
  if (ids.length === 0) problems.push('manifest.json lists no templates');

  const stockIds = liquidIds(p.stockDir);
  const brandedIds = liquidIds(p.dir);
  const skipped = new Set(ids.filter((id) => manifest.templates[id].skip));
  const expectedBranded = ids.filter((id) => !skipped.has(id));

  for (const id of ids) if (!stockIds.includes(id)) problems.push(`${id}: stock/${id}.liquid is missing`);
  for (const id of stockIds) if (!ids.includes(id)) problems.push(`${id}: stock/${id}.liquid is not in manifest.json`);
  for (const id of brandedIds) {
    if (!ids.includes(id)) problems.push(`${id}: ${id}.liquid has no manifest entry`);
    else if (skipped.has(id)) problems.push(`${id}: marked skip in manifest.json but ${id}.liquid exists`);
  }

  const css = readFileSync(p.css, 'utf8');
  const social = readFileSync(p.social, 'utf8');
  if (!css.endsWith('\n')) problems.push('lib/brand-style.css must end with a newline');
  for (const [name, text] of [['lib/brand-style.css', css], ['lib/footer-social.html', social]]) {
    if (text.includes('\r')) problems.push(`${name} contains a carriage return`);
  }

  for (const id of ids) {
    const entry = manifest.templates[id];
    if (!stockIds.includes(id)) continue;
    const stock = readFileSync(p.stock(id), 'utf8');
    if (typeof entry.stockSha256 !== 'string' || typeof entry.stockLength !== 'number') {
      problems.push(`${id}: manifest entry lacks stockSha256 / stockLength`);
      continue;
    }
    if (stock.length !== entry.stockLength || sha256(stock) !== entry.stockSha256) {
      problems.push(
        `${id}: stock/${id}.liquid does not match the recorded snapshot (length ${stock.length}, expected ${entry.stockLength}); ` +
          're-record it with scripts/notifications/record-stock.mjs if the change is intended',
      );
      continue;
    }
    if (skipped.has(id)) {
      notes.push(`${id}: skipped (${entry.skip})`);
      continue;
    }
    try {
      const { output, accentRemaining } = brandTemplate(stock, { id, css, social, override: entry.override });
      outputs.set(id, output);
      if (accentRemaining > 0) notes.push(`${id}: ${accentRemaining} email_accent_color reference(s) remain in the body`);
    } catch (err) {
      if (err instanceof BrandError) problems.push(err.message);
      else throw err;
    }
  }
  return { outputs, problems, notes, expectedBranded };
}

function firstDifference(actual, expected) {
  const len = Math.min(actual.length, expected.length);
  let i = 0;
  while (i < len && actual[i] === expected[i]) i++;
  const line = actual.slice(0, i).split('\n').length;
  const ctx = (s) => s.slice(Math.max(0, i - 60), i + 60).replace(/\n/g, '\\n');
  return { offset: i, line, expected: ctx(expected), actual: ctx(actual) };
}

export function check(root = REPO_ROOT) {
  const p = paths(root);
  const { outputs, problems, notes, expectedBranded } = plan(root);
  const mismatches = [];
  for (const id of expectedBranded) {
    if (!outputs.has(id)) continue;
    if (!existsSync(p.branded(id))) {
      mismatches.push(`${id}: ${id}.liquid is missing`);
      continue;
    }
    const actual = readFileSync(p.branded(id), 'utf8');
    const expected = outputs.get(id);
    if (Buffer.compare(Buffer.from(actual, 'utf8'), Buffer.from(expected, 'utf8')) !== 0) {
      const d = firstDifference(actual, expected);
      mismatches.push(
        `${id}: ${id}.liquid differs from regenerated output at offset ${d.offset} (line ${d.line})\n` +
          `    expected: ...${d.expected}...\n    actual:   ...${d.actual}...`,
      );
    }
  }
  return { problems, mismatches, notes };
}

export function generate(root = REPO_ROOT) {
  const p = paths(root);
  const { outputs, problems, notes } = plan(root);
  if (problems.length > 0) return { problems, written: [], notes };
  const written = [];
  for (const [id, output] of outputs) {
    const target = p.branded(id);
    const tmp = `${target}.tmp`;
    writeFileSync(tmp, output, 'utf8');
    renameSync(tmp, target);
    written.push(id);
  }
  return { problems, written, notes };
}

function main(argv) {
  const args = argv.slice(2);
  const checkMode = args.includes('--check');
  const rootFlag = args.indexOf('--root');
  const root = rootFlag !== -1 ? resolve(args[rootFlag + 1]) : REPO_ROOT;
  if (checkMode) {
    const { problems, mismatches, notes } = check(root);
    for (const n of notes) console.log(`note: ${n}`);
    for (const m of problems) console.error(`error: ${m}`);
    for (const m of mismatches) console.error(`error: ${m}`);
    if (problems.length || mismatches.length) {
      console.error(
        `notifications:check failed: ${problems.length} problem(s), ${mismatches.length} file(s) out of date. Fix: npm run notifications:generate`,
      );
      return 1;
    }
    console.log('notifications:check ok');
    return 0;
  }
  const { problems, written, notes } = generate(root);
  for (const n of notes) console.log(`note: ${n}`);
  for (const m of problems) console.error(`error: ${m}`);
  if (problems.length) {
    console.error(`notifications:generate refused: ${problems.length} problem(s); nothing written`);
    return 1;
  }
  console.log(`notifications:generate wrote ${written.length} file(s)`);
  return 0;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exitCode = main(process.argv);
}
