// Differential tests for the crop proposer. Each tuning constant that exists because a real run
// failed is exercised TWICE: once neutralized, asserting the known-bad outcome, and once at the
// default. A single-run assertion cannot tell a working constant from a decorative one.
//
// Fixtures are committed and generated by `crops.mjs --emit-fixture`:
//   fixtures/autocrop/*.png       four archetype cells reduced to the 200x200 work grid by the
//                                 same box-average the algorithm applies, so a fixture reproduces
//                                 the full-resolution proposal rather than approximating it
//   fixtures/scan-tiles.json      the real 18 crops' tile matrices, plus known-bad corner crops

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  AUTOCROP_DEFAULTS, SUSPECT_SD, classifyTiles, erode, largestInscribedSquare, otsuThreshold,
  percentile, proposeBox, toWorkGrid,
} from '../lib/autocrop.mjs';
import { loadSharp } from '../lib/compose.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const FIXTURES = path.join(HERE, 'fixtures');
const meta = JSON.parse(readFileSync(path.join(FIXTURES, 'autocrop', 'archetypes.json'), 'utf8'));
const scan = JSON.parse(readFileSync(path.join(FIXTURES, 'scan-tiles.json'), 'utf8'));

const byArchetype = new Map(meta.archetypes.map((a) => [a.archetype, a]));

async function archetype(name) {
  const rec = byArchetype.get(name);
  assert.ok(rec, `no fixture for archetype ${name}`);
  const sharp = await loadSharp();
  const { data, info } = await sharp(path.join(FIXTURES, 'autocrop', rec.file))
    .raw().toBuffer({ resolveWithObject: true });
  return { image: { data, width: info.width, height: info.height, channels: info.channels }, rec };
}

// Deterministic noise: Math.random would make a failure unreproducible.
function mulberry32(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function synthetic(width, height, fill) {
  const data = Buffer.alloc(width * height * 3);
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const [r, g, b] = fill(x, y);
      const i = (y * width + x) * 3;
      data[i] = r; data[i + 1] = g; data[i + 2] = b;
    }
  }
  return { data, width, height, channels: 3 };
}

const centre = (b) => ({ x: b.left + b.size / 2, y: b.top + b.size / 2 });
const contains = (b, p) => p.x >= b.left && p.x <= b.left + b.size && p.y >= b.top && p.y <= b.top + b.size;

// ---------------------------------------------------------------------------
// Fixture fidelity: without this, everything below could be measuring the fixture format.
// ---------------------------------------------------------------------------

test('each archetype fixture reproduces the full-resolution proposal it was derived from', async () => {
  for (const rec of meta.archetypes) {
    const { image } = await archetype(rec.archetype);
    const got = proposeBox(image);
    const want = rec.fullResolutionProposal;
    assert.ok(got && want, `${rec.archetype}: both proposals must resolve`);
    for (const k of ['left', 'top', 'size']) {
      assert.ok(
        Math.abs(got[k] - want[k]) <= 0.01,
        `${rec.archetype}.${k}: fixture ${got[k]} vs full resolution ${want[k]}`,
      );
    }
  }
});

test('every returned box is a normalized square inside the frame', async () => {
  for (const rec of meta.archetypes) {
    const { image } = await archetype(rec.archetype);
    const b = proposeBox(image);
    assert.ok(b, `${rec.archetype} must resolve`);
    assert.equal(b.width, b.height, `${rec.archetype}: proposals are square in normalized space`);
    assert.equal(b.width, b.size);
    assert.ok(b.left >= 0 && b.top >= 0, `${rec.archetype}: left/top non-negative`);
    assert.ok(b.left + b.size <= 1 + 1e-9, `${rec.archetype}: left + size <= 1`);
    assert.ok(b.top + b.size <= 1 + 1e-9, `${rec.archetype}: top + size <= 1`);
    assert.ok(b.size > 0 && b.size <= 1);
  }
});

// ---------------------------------------------------------------------------
// Differentials: neutralized constant first, so the test states what the constant prevents.
// ---------------------------------------------------------------------------

test('saturation floor: satFloor 0 wrecks the proposal on an achromatic print', async () => {
  const { image } = await archetype('achromatic-paw');
  const good = proposeBox(image);
  const bad = proposeBox(image, { satFloor: 0 });

  // Known-bad: dividing by the chroma NOISE of a black-and-white print amplifies that noise into
  // the dominant cue, and the fabric region stops driving the result at all.
  assert.ok(bad, 'the neutralized run still returns a box, which is what makes it dangerous');
  assert.ok(
    bad.size < good.size * 0.5,
    `neutralized box should collapse (got ${bad.size} vs ${good.size})`,
  );
  assert.ok(!contains(bad, centre(good)), 'the neutralized box should not even contain the good box centre');

  // Default: a box covering most of the fabric panel, well inside the frame.
  assert.ok(good.size > 0.5, `default proposal should cover the fabric panel, got ${good.size}`);
  assert.ok(good.diagnostics.satP95 < AUTOCROP_DEFAULTS.satFloor, 'this archetype is achromatic by construction');
});

test('stddev floor: sdFloor 0 invents a box on a frame that is pure sensor noise', () => {
  const rnd = mulberry32(20260813);
  const flat = synthetic(400, 533, () => {
    const v = 128 + Math.round((rnd() - 0.5) * 4);
    return [v, v, v];
  });
  assert.equal(proposeBox(flat), null, 'a flat noisy frame is unresolvable at the default floor');
  assert.notEqual(proposeBox(flat, { sdFloor: 0 }), null, 'without the floor, noise normalizes to signal');
});

test('smoothing radius: a smaller radius collapses the inscribed square', async () => {
  for (const name of ['cream-print', 'youll-live']) {
    const { image } = await archetype(name);
    const good = proposeBox(image);
    const r1 = proposeBox(image, { smoothRadius: 1 });
    const r4 = proposeBox(image, { smoothRadius: 4 });
    assert.ok(good, `${name}: default must resolve`);
    // Radius 1 thresholds to confetti that holds almost no square. Radius 4 is the case a
    // single-run assertion could never distinguish from radius 8, which is why it is here.
    assert.ok(
      !r1 || r1.diagnostics.side < good.diagnostics.side * 0.5,
      `${name}: radius 1 side ${r1?.diagnostics.side} vs default ${good.diagnostics.side}`,
    );
    assert.ok(
      !r4 || r4.diagnostics.side < good.diagnostics.side * 0.75,
      `${name}: radius 4 side ${r4?.diagnostics.side} vs default ${good.diagnostics.side}`,
    );
  }
});

test('otsu-cap regression: Math.min(otsu, 0.18) makes a cream print grab the table', async () => {
  const { image } = await archetype('cream-print');
  const good = proposeBox(image);
  const capped = proposeBox(image, { otsuCap: 0.18 });
  assert.ok(good && capped);

  // Known-bad: the cap lowers the threshold under the slightly-off-cream tabletop, so EVERY cell
  // classifies as fabric and the box becomes the whole frame. This photo's upper third is pure
  // backdrop, so a box starting near the top edge is grabbing the table by construction.
  assert.equal(capped.diagnostics.coverage, 1, 'the capped run classifies the entire frame as fabric');
  assert.ok(capped.top < 0.1, `capped box starts at the frame top (${capped.top}), which is table`);
  assert.ok(capped.size > 0.85, `capped box spans the frame (${capped.size})`);

  // Default: the threshold stays above the table, so the box starts inside the fabric panel.
  assert.ok(good.diagnostics.coverage < 0.8, `default coverage ${good.diagnostics.coverage}`);
  assert.ok(good.top > 0.35, `default box starts below the backdrop (${good.top})`);
  assert.equal(AUTOCROP_DEFAULTS.otsuCap, null, 'the cap must stay off in production');
});

// ---------------------------------------------------------------------------
// Geometry
// ---------------------------------------------------------------------------

test('work grid box-averages the source and reports saturation per cell', () => {
  // Left half pure red, right half mid grey: greyscale and saturation must both split at x = 0.5.
  const img = synthetic(40, 60, (x) => (x < 20 ? [255, 0, 0] : [128, 128, 128]));
  const { grid, grey, sat } = toWorkGrid(img, 4);
  assert.equal(grid, 4);
  assert.equal(sat[0], 255);
  assert.equal(sat[3], 0);
  assert.ok(Math.abs(grey[0] - 0.299 * 255) < 1e-6);
  assert.ok(Math.abs(grey[3] - 128) < 1e-6);
});

test('a fully covered mask yields size 0.9: the 5 percent inset, applied on each side', () => {
  const grid = 20;
  const mask = new Uint8Array(grid * grid).fill(1);
  const sq = largestInscribedSquare(mask, grid);
  assert.deepEqual(sq, { row: 0, col: 0, side: grid });

  // Same thing end to end: a frame that is textured everywhere, with erosion neutralized so the
  // only thing trimming the square is the inset.
  const checker = synthetic(200, 200, (x, y) => {
    const v = ((x >> 1) + (y >> 1)) % 2 ? 20 : 235;
    return [v, v, v];
  });
  const b = proposeBox(checker, { erodeRadius: 0 });
  assert.ok(b);
  assert.equal(b.size, 0.9);
  assert.equal(b.left, 0.05);
  assert.equal(b.top, 0.05);
});

test('erosion pulls the survivor set off the frame border', () => {
  const grid = 12;
  const mask = new Uint8Array(grid * grid).fill(1);
  const eroded = erode(mask, grid, 2);
  assert.equal(eroded[0], 0, 'the corner cell cannot survive a window that leaves the frame');
  assert.equal(eroded[2 * grid + 2], 1);
  assert.deepEqual(largestInscribedSquare(eroded, grid), { row: 2, col: 2, side: grid - 4 });
});

test('an unresolvable image returns the null sentinel, not a plausible-looking box', () => {
  assert.equal(proposeBox(synthetic(120, 160, () => [200, 200, 200])), null, 'all-flat cell');
  assert.equal(proposeBox(synthetic(120, 160, (x, y) => [x % 3, y % 3, 0])), null, 'no usable signal');
});

test('percentile and otsu behave on the degenerate inputs the pipeline can hand them', () => {
  assert.equal(percentile([], 95), 0);
  assert.equal(percentile([5], 95), 5);
  assert.equal(percentile([1, 2, 3, 4, 5], 50), 3);
  assert.equal(otsuThreshold([]), 0);
  assert.equal(otsuThreshold([0.4, 0.4, 0.4]), 0, 'no spread means no split');
});

// ---------------------------------------------------------------------------
// The backdrop screen
// ---------------------------------------------------------------------------

test('classifyTiles names the offending tile, its edge, and the margin', () => {
  const matrix = new Array(100).fill(30);
  matrix[7] = 4.2;                        // row 0, col 7: the top edge
  const c = classifyTiles(matrix);
  assert.equal(c.suspect, true);
  assert.equal(c.tile, 7);
  assert.equal(c.row, 0);
  assert.equal(c.col, 7);
  assert.equal(c.edge, 'top');
  assert.ok(Math.abs(c.minSd - 4.2) < 1e-9);

  const corner = new Array(100).fill(30);
  corner[99] = 1;
  assert.equal(classifyTiles(corner).edge, 'bottom-right');
  const inner = new Array(100).fill(30);
  inner[55] = 1;
  assert.equal(classifyTiles(inner).edge, 'interior');
});

test('classifyTiles brackets the threshold rather than merely crossing it', () => {
  const wedge = new Array(100).fill(40);
  wedge[12] = 11;
  const clean = classifyTiles(wedge);
  assert.equal(clean.suspect, false, 'a genuinely flat-ish fabric tile at sd 11 is not a suspect');
  wedge[12] = 9;
  assert.equal(classifyTiles(wedge).suspect, true);
  assert.equal(SUSPECT_SD, 10);
});

test('classifyTiles refuses a malformed matrix instead of guessing', () => {
  assert.throws(() => classifyTiles(new Array(99).fill(1)), /expected 100/);
  assert.throws(() => classifyTiles([...new Array(99).fill(1), NaN]), /not a finite number/);
});

test('the committed 18-crop matrices keep their margin over the threshold', () => {
  // Informational, and allowed to SHRINK: improving the detector must not be a test failure. It
  // may not GROW without someone looking at why.
  const knownFalsePositives = new Set(['forever-stripes']);
  const seen = new Set();
  for (const e of scan.entries) {
    const c = classifyTiles(e.matrix, { tiles: scan.tiles, threshold: scan.threshold });
    if (c.suspect) {
      seen.add(e.patternId);
      assert.ok(
        knownFalsePositives.has(e.patternId),
        `${e.patternId} is a new suspect (min tile sd ${c.minSd}); the crop or the metric moved`,
      );
      continue;
    }
    assert.ok(
      c.minSd >= 10.5,
      `${e.patternId} passes at ${c.minSd}, with almost no margin; a metric shift would flip it`,
    );
  }
  for (const id of seen) assert.ok(knownFalsePositives.has(id));
  const youllLive = scan.entries.find((e) => e.patternId === 'youll-live');
  assert.ok(youllLive, 'the recropped You\'ll Live case must stay in the fixture');
  assert.ok(classifyTiles(youllLive.matrix).minSd >= 11, 'You\'ll Live is the tightest clean crop');
});

test('the known-bad corner crops are caught, with margin', () => {
  assert.ok(scan.knownBad.length >= 4);
  for (const e of scan.knownBad) {
    const c = classifyTiles(e.matrix, { tiles: scan.tiles, threshold: scan.threshold });
    assert.equal(c.suspect, true, `${e.archetype} is backdrop by construction`);
    assert.ok(c.minSd <= 8, `${e.archetype} should be caught by a wide margin, got ${c.minSd}`);
  }
});
