// Tier C checks: the operator checklist. Rendered into the run file; the skill reads back only
// checkbox state and evidence fields. Side effects: real (test-mode) orders, inventory movement,
// notifications. The `group` field orders the run file; `vacationOnly` items render only while
// vacation mode is on.

export const C_CHECKS = [
  { id: 'c-orders-precondition', tier: 'C', surface: 'orders', severity: 'ERROR', group: 'test-orders', description: 'Store gated or a scheduled window; test mode on; low-stock alert Flow paused.' },
  { id: 'c-orders-under-threshold', tier: 'C', surface: 'orders', severity: 'ERROR', group: 'test-orders', description: 'Garment order under the free-shipping threshold is charged the flat rate.' },
  { id: 'c-orders-over-threshold', tier: 'C', surface: 'orders', severity: 'ERROR', group: 'test-orders', description: 'Garment order at or over the threshold ships free.' },
  { id: 'c-orders-gift-card-only', tier: 'C', surface: 'orders', severity: 'ERROR', group: 'test-orders', description: 'Gift-card-only order has no shipping line and emails the card.' },
  { id: 'c-orders-mixed', tier: 'C', surface: 'orders', severity: 'ERROR', group: 'test-orders', description: 'Mixed cart: the gift card value does not count toward free shipping.' },
  { id: 'c-orders-expedited', tier: 'C', surface: 'orders', severity: 'ERROR', group: 'test-orders', description: 'Expedited rate offered at the weight tier expected for the cart.' },
  { id: 'c-orders-discount-code', tier: 'C', surface: 'orders', severity: 'ERROR', group: 'test-orders', description: 'A discount code applies at checkout (cart disclosure is off).' },
  { id: 'c-orders-express-wallet', tier: 'C', surface: 'orders', severity: 'ERROR', group: 'test-orders', description: 'An express wallet checkout carries the acknowledgment properties.' },
  { id: 'c-orders-properties', tier: 'C', surface: 'orders', severity: 'ERROR', group: 'test-orders', description: 'Applique, custom text and acknowledgment properties appear on the order.' },
  { id: 'c-orders-note', tier: 'C', surface: 'orders', severity: 'ERROR', group: 'test-orders', description: 'An order note reaches the order.' },
  { id: 'c-orders-teardown', tier: 'C', surface: 'orders', severity: 'ERROR', group: 'test-orders', description: 'Every test order tagged test-order, cancelled with restock; issued gift cards deactivated; test mode confirmed off.' },
  { id: 'c-lifecycle-capture', tier: 'C', surface: 'lifecycle', severity: 'ERROR', group: 'post-order', description: 'Payment capture (manual or automatic per the Admin setting).' },
  { id: 'c-lifecycle-fulfil', tier: 'C', surface: 'lifecycle', severity: 'ERROR', group: 'post-order', description: 'Fulfil with tracking; the shipping confirmation carries the tracking link.' },
  { id: 'c-lifecycle-partial-refund', tier: 'C', surface: 'lifecycle', severity: 'ERROR', group: 'post-order', description: 'Partial refund; refund notification.' },
  { id: 'c-lifecycle-cancel', tier: 'C', surface: 'lifecycle', severity: 'ERROR', group: 'post-order', description: 'Cancel with restock; inventory returns.' },
  { id: 'c-lifecycle-return', tier: 'C', surface: 'lifecycle', severity: 'ERROR', group: 'post-order', description: 'Return flow from the account page.' },
  { id: 'c-lifecycle-reorder', tier: 'C', surface: 'lifecycle', severity: 'ERROR', group: 'post-order', description: 'Reorder from the account order page.' },
  { id: 'c-notifications-received', tier: 'C', surface: 'notifications', severity: 'ERROR', group: 'notifications', description: 'Every notification in the waves listed in marketing/notifications/README.md arrives, branded or stock as recorded.' },
  { id: 'c-notifications-headers', tier: 'C', surface: 'notifications', severity: 'ERROR', group: 'notifications', description: 'Authentication-Results headers pass; sender and reply-to are the brand addresses.' },
  { id: 'c-forms-contact', tier: 'C', surface: 'forms', severity: 'ERROR', group: 'forms', description: 'Contact form submits through hCaptcha and the message arrives.' },
  { id: 'c-forms-request-combination', tier: 'C', surface: 'forms', severity: 'ERROR', group: 'forms', description: 'Request-combination submits on each of its three paths.' },
  { id: 'c-forms-newsletter', tier: 'C', surface: 'forms', severity: 'ERROR', group: 'forms', description: 'Newsletter signup (footer and password page) subscribes and the welcome automation sends.' },
  { id: 'c-forms-blog-comment', tier: 'C', surface: 'forms', severity: 'WARN', group: 'forms', description: 'Blog comment form, if the blog is in use.' },
  { id: 'c-accounts-signup', tier: 'C', surface: 'accounts', severity: 'ERROR', group: 'accounts', description: 'Customer sign up.' },
  { id: 'c-accounts-login', tier: 'C', surface: 'accounts', severity: 'ERROR', group: 'accounts', description: 'Login code arrives and signs in.' },
  { id: 'c-accounts-order-view', tier: 'C', surface: 'accounts', severity: 'ERROR', group: 'accounts', description: 'A placed order is visible in the account.' },
  { id: 'c-accounts-addresses', tier: 'C', surface: 'accounts', severity: 'ERROR', group: 'accounts', description: 'Address add, edit and delete.' },
  { id: 'c-accounts-marketing', tier: 'C', surface: 'accounts', severity: 'ERROR', group: 'accounts', description: 'Marketing opt-in state round-trips.' },
  { id: 'c-flow-low-stock', tier: 'C', surface: 'flow', severity: 'ERROR', group: 'flow', description: 'Low stock alert Flow fires at the threshold (after re-enabling).' },
  { id: 'c-flow-auto-cancel', tier: 'C', surface: 'flow', severity: 'ERROR', group: 'flow', description: 'Auto cancel Flow scope matches the intended orders only.' },
  { id: 'c-flow-inventory-sync', tier: 'C', surface: 'flow', severity: 'ERROR', group: 'flow', description: 'Inventory-sync fan-out reaches sibling variants after a test order.' },
  { id: 'c-admin-capture-mode', tier: 'C', surface: 'admin-settings', severity: 'ERROR', group: 'admin-settings', description: 'Payment capture mode is the intended one.' },
  { id: 'c-admin-gift-card-expiry', tier: 'C', surface: 'admin-settings', severity: 'ERROR', group: 'admin-settings', description: 'Gift-card expiry setting is the intended one.' },
  { id: 'c-admin-checkout-account', tier: 'C', surface: 'admin-settings', severity: 'ERROR', group: 'admin-settings', description: 'Checkout customer-account requirement is the intended one.' },
  { id: 'c-admin-notification-sender', tier: 'C', surface: 'admin-settings', severity: 'ERROR', group: 'admin-settings', description: 'Notification sender address is the brand address.' },
  { id: 'c-admin-skipped-reads', tier: 'C', surface: 'admin-settings', severity: 'ERROR', group: 'admin-settings', description: 'Every A2 read skipped for a missing scope, verified by hand in Admin (listed by name).' },
  { id: 'c-devices-ios', tier: 'C', surface: 'devices', severity: 'ERROR', group: 'devices', description: 'iOS Safari pass over product, cart and checkout.' },
  { id: 'c-devices-android', tier: 'C', surface: 'devices', severity: 'ERROR', group: 'devices', description: 'Android Chrome pass over product, cart and checkout.' },
  { id: 'c-devices-apple-wallet', tier: 'C', surface: 'devices', severity: 'ERROR', group: 'devices', description: 'Gift card adds to Apple Wallet.' },
  { id: 'c-launch-smoke-public', tier: 'C', surface: 'launch', severity: 'ERROR', group: 'launch', description: 'After password removal the deploy smoke runs in PUBLIC mode (verification only; the task stays in TODO.md).' },
  { id: 'c-launch-a1-public', tier: 'C', surface: 'launch', severity: 'ERROR', group: 'launch', description: 'After password removal Tier A1 passes in PUBLIC mode.' },
  { id: 'c-vacation-surfaces', tier: 'C', surface: 'vacation', severity: 'ERROR', group: 'vacation', vacationOnly: true, description: 'Popup, checkbox terms, shipping note and processing date all show the same date; the FAQ deep link resolves.' },
];
